# -*- coding: utf-8 -*-
"""Diccionarios1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gm0tJcIu_ztYJKdJyum-AB01Wsm-8r7B
"""

# --------------------------------------------------
# 1. CREAR DICCIONARIOS
# --------------------------------------------------
# Se define e inicializa el primer diccionario 'sensors' asignando a cada habitación (clave) una temperatura (valor).
# Luego se crea 'num_cameras' con ubicaciones y sus cantidades correspondientes.
# Finalmente, se imprimen ambos diccionarios completos en la consola.

sensors = {
    "living room": 21,
    "kitchen": 23,
    "bedroom": 20,
    "pantry": 22
}

num_cameras = {
    "backyard": 6,
    "garage": 2,
    "driveway": 1
}

print(sensors)
print(num_cameras)

# --------------------------------------------------
# 2. DICCIONARIO CON TRADUCCIONES
# --------------------------------------------------
# Se crea un diccionario donde las claves son palabras en inglés y los valores son sus traducciones en Sindarin (élfico).
# Se muestra el diccionario de traducciones completo en la pantalla.

translations = {
    "mountain": "orod",
    "bread": "bass",
    "friend": "mellon",
    "horse": "roch"
}

print(translations)

# --------------------------------------------------
# 3. ERROR AL UTILIZAR LISTAS COMO CLAVES
# --------------------------------------------------
# Este bloque demuestra una regla clave en Python: las listas son mutables (se pueden alterar),
# por lo que no pueden usarse como claves en un diccionario. El código está comentado para no detener la ejecución por error.

# Este código produciría un error:
#
# powers = {
#     [1, 2, 4, 8, 16]: 2,
#     [1, 3, 9, 27, 81]: 3
# }
#
# Las listas NO pueden utilizarse como claves de un
# diccionario porque son modificables (mutables).
#
# Por eso este código está comentado.

# --------------------------------------------------
# 4. DICCIONARIO CON LISTAS COMO VALORES
# --------------------------------------------------
# Muestra que aunque las listas no pueden ser claves, sí pueden ser valores de un diccionario.
# Aquí las familias son las claves y las listas de sus hijos son los valores.
# Se imprime la estructura resultante.

children = {
    "von Trapp": ["Johannes", "Rosmarie", "Eleonore"],
    "Corleone": ["Sonny", "Fredo", "Michael"]
}

print(children)

# --------------------------------------------------
# 5. DICCIONARIO VACÍO
# --------------------------------------------------
# Se declara una variable con un diccionario totalmente vacío utilizando únicamente las llaves `{}`.
# Se imprime para verificar que la estructura existe pero no contiene elementos.

my_empty_dictionary = {}

print(my_empty_dictionary)

# --------------------------------------------------
# 6. AGREGAR UN ELEMENTO A UN DICCIONARIO
# --------------------------------------------------
# Se define un menú con platillos y precios, mostrándolo inicialmente.
# Se inserta un nuevo par clave-valor ("cheesecake": 8) mediante la sintaxis de corchetes `menu["clave"] = valor`.
# Se imprime el menú actualizado para confirmar la inclusión.

menu = {
    "oatmeal": 3,
    "avocado toast": 6,
    "carrot juice": 5,
    "blueberry muffin": 2
}

print("Before:", menu)

menu["cheesecake"] = 8

print("After:", menu)

# --------------------------------------------------
# 7. CAMBIAR EL VALOR DE UN DICCIONARIO
# --------------------------------------------------
# Se demuestra la reasignación total de la variable.
# Al asignar una nueva estructura a `animals_in_zoo`, se destruye el objeto previo ("dinosaurs") y solo se conserva el nuevo ("horses").
# Se imprime la variable mostrando la sustitución completa.

animals_in_zoo = {
    "dinosaurs": 0
}

animals_in_zoo = {
    "horses": 2
}

print(animals_in_zoo)

# --------------------------------------------------
# 8. AGREGAR VARIAS CLAVES CON update()
# --------------------------------------------------
# A partir de un diccionario básico 'sensors', se utiliza el método `.update()` pasando otro diccionario como argumento.
# Esto permite agregar múltiples pares clave-valor en una sola instrucción.
# Se imprimen los estados antes y después de aplicar el método.

sensors = {
    "living room": 21,
    "kitchen": 23,
    "bedroom": 20
}

print("Before:", sensors)

sensors.update({
    "pantry": 22,
    "guest room": 25,
    "patio": 34
})

print("After:", sensors)

# --------------------------------------------------
# 9. OTRO EJEMPLO DE update()
# --------------------------------------------------
# Se inicia con un diccionario de usuarios e identificadores numéricos.
# Se invoca `.update()` para incluir recursivamente dos perfiles de usuario adicionales al registro.
# Se muestra la lista de IDs actualizada.

user_ids = {
    "teraCoder": 9018293,
    "proProgrammer": 119238
}

print(user_ids)

user_ids.update({
    "theLooper": 138475,
    "stringQueen": 85739
})

print(user_ids)

# --------------------------------------------------
# 10. SOBRESCRIBIR UN VALOR
# --------------------------------------------------
# Al asignar un valor a una clave que YA existe en el diccionario (`menu["oatmeal"] = 5`),
# Python reemplaza el dato antiguo (3) por el nuevo (5) en lugar de crear un duplicado.
# Se verifica la modificación imprimiendo el resultado final.

menu = {
    "oatmeal": 3,
    "avocado toast": 6,
    "carrot juice": 5,
    "blueberry muffin": 2
}

print("Before:", menu)

menu["oatmeal"] = 5

print("After:", menu)

# --------------------------------------------------
# 11. AGREGAR Y MODIFICAR CON update()
# --------------------------------------------------
# Muestra la versatilidad de `.update()` y el acceso por clave.
# Primero usa `.update()` para agregar una categoría inexistente ("Supporting Actress").
# Después reasigna mediante corchetes el valor de "Best Picture" de "La La Land" a "Moonlight".

oscar_winners = {
    "Best Picture": "La La Land",
    "Best Actor": "Casey Affleck",
    "Best Actress": "Emma Stone",
    "Animated Feature": "Zootopia"
}

print("Before:", oscar_winners)
print()

oscar_winners.update({
    "Supporting Actress": "Viola Davis"
})

print("After1:", oscar_winners)
print()

oscar_winners["Best Picture"] = "Moonlight"

print("After2:", oscar_winners)

# --------------------------------------------------
# 12. DICT COMPREHENSION
# --------------------------------------------------
# Declara dos listas independientes con el mismo número de elementos e índices correspondientes:
# una para nombres de estudiantes (`names`) y otra para sus respectivas alturas (`heights`).

names = [
    "Jenny",
    "Alexus",
    "Sam",
    "Grace"
]

heights = [
    61,
    70,
    67,
    64
]

# --------------------------------------------------
# 13. zip()
# --------------------------------------------------
# Se utiliza la función integrada `zip()` para entrelazar los elementos pares de las listas `names` y `heights`.
# La variable almacena un objeto generador iterador 'zip', el cual se imprime para observar su referencia en memoria.

names = ["Jenny", "Alexus", "Sam", "Grace"]
heights = [61, 70, 67, 64]

zipStudents = zip(names, heights)

print("zipStudents:", zipStudents)

# --------------------------------------------------
# 14. CREAR UN DICCIONARIO CON zip()
# --------------------------------------------------
# Se aplica una compresión de diccionarios (Dict Comprehension) iterando sobre las parejas generadas por `zip(names, heights)`.
# Asigna cada nombre como clave y cada altura como valor, construyendo el diccionario final.

names = ["Jenny", "Alexus", "Sam", "Grace"]
heights = [61, 70, 67, 64]

students = {
    key: value
    for key, value in zip(names, heights)
}

print(students)

# --------------------------------------------------
# 15. OTRO EJEMPLO DE zip()
# --------------------------------------------------
# Se vincula una lista de bebidas con sus miligramos de cafeína usando `zip()`.
# Mediante compresión de diccionarios se iteran los pares para construir el mapa funcional `drinks_to_caffeine` y se imprime.

drinks = [
    "espresso",
    "chai",
    "decaf",
    "drip"
]

caffeine = [
    64,
    40,
    0,
    120
]

zipped_drinks = zip(drinks, caffeine)

print(zipped_drinks)

drinks_to_caffeine = {
    key: value
    for key, value in zipped_drinks
}

print(drinks_to_caffeine)

# --------------------------------------------------
# 16. EJEMPLO FINAL: CANCIONES Y REPRODUCCIONES
# --------------------------------------------------
# Se crean dos listas fuente para estructurar datos complejos: una con títulos de canciones y otra con los números de reproducciones asociados.

songs = [
    "Like a Rolling Stone",
    "Satisfaction",
    "Imagine",
    "What's Going On",
    "Respect",
    "Good Vibrations"
]

playcounts = [
    78,
    29,
    44,
    21,
    89,
    5
]

# --------------------------------------------------
# 17. CREAR EL DICCIONARIO plays
# --------------------------------------------------
# Se empaquetan las listas `songs` y `playcounts` utilizando `zip()` dentro de una dict comprehension.
# Se asigna el resultado a la variable `plays` y se muestra el mapa ordenado por pantalla.

songs = ["Like a Rolling Stone", "Satisfaction", "Imagine", "What's Going On", "Respect", "Good Vibrations"]
playcounts = [78, 29, 44, 21, 89, 5]

plays = {
    key: value
    for key, value in zip(songs, playcounts)
}

print(plays)

# --------------------------------------------------
# 18. AGREGAR UNA NUEVA CANCIÓN
# --------------------------------------------------
# Se actualiza la colección `plays` llamando al método `.update()` para insertar una canción no registrada ("Purple Haze") con 1 reproducción.

plays = {
    "Like a Rolling Stone": 78,
    "Satisfaction": 29,
    "Imagine": 44,
    "What's Going On": 21,
    "Respect": 89,
    "Good Vibrations": 5
}

plays.update({
    "Purple Haze": 1
})

# --------------------------------------------------
# 19. MODIFICAR UNA CANCIÓN EXISTENTE
# --------------------------------------------------
# Se ejecuta `.update()` pasando una clave que ya existía en el diccionario ("Respect").
# Como la clave se encuentra presente, modifica el conteo preexistente de 89 a 94 reproducciones.
# Se imprime el diccionario para confirmar la modificación.

plays = {
    "Like a Rolling Stone": 78,
    "Satisfaction": 29,
    "Imagine": 44,
    "What's Going On": 21,
    "Respect": 89,
    "Good Vibrations": 5,
    "Purple Haze": 1
}

plays.update({
    "Respect": 94
})

print("After:", plays)

# --------------------------------------------------
# 20. DICCIONARIO DENTRO DE OTRO DICCIONARIO
# --------------------------------------------------
# Muestra la anidación de diccionarios. Se crea el diccionario `library` que contiene como valor de una clave a otro diccionario entero (`plays`),
# y como valor de otra clave a un diccionario vacío (`{}`).
# Se imprime la estructura anidada completa.

plays = {
    "Like a Rolling Stone": 78,
    "Satisfaction": 29,
    "Imagine": 44,
    "What's Going On": 21,
    "Respect": 94,
    "Good Vibrations": 5,
    "Purple Haze": 1
}

library = {
    "The Best Songs": plays,
    "Sunday Feelings": {}
}

print(library)