# -*- coding: utf-8 -*-
"""Diccionarios2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EpNYgt307DVPHVKWiwa1_hF82tQ-mh5L
"""

# ==================================================
# 1. EXPLICACIÓN
# ==================================================
# Se crea un diccionario llamado 'building_heights' que asigna el nombre de varios edificios
# como clave y su altura en metros como valor.
# Luego, se accede e imprime el valor de alturas específicas usando directamente su clave entre corchetes
# como `building_heights["Burj Khalifa"]`.

building_heights = {
    "Burj Khalifa": 828,
    "Shanghai Tower": 632,
    "Abraj Al Bait": 601,
    "Ping An": 599,
    "Lotte World Tower": 554.5,
    "One World Trade": 541.3
}

print(building_heights["Burj Khalifa"])
print(building_heights["Ping An"])

# ==================================================
# 2. EXPLICACIÓN
# ==================================================
# Se define un diccionario donde las claves son los elementos del zodiaco y los valores son listas con signos.
# Se accede directamente a las claves `"earth"` y `"fire"` utilizando corchetes, lo que devuelve
# e imprime las listas completas asociadas a cada una.

zodiac_elements = {
    "water": ["Cancer", "Scorpio", "Pisces"],
    "fire": ["Aries", "Leo", "Sagittarius"],
    "earth": ["Taurus", "Virgo", "Capricorn"],
    "air": ["Gemini", "Libra", "Aquarius"]
}

print(zodiac_elements["earth"])
print(zodiac_elements["fire"])

# ==================================================
# 3. EXPLICACIÓN
# ==================================================
# Se explica qué ocurre al intentar acceder a una clave mediante corchetes cuando esta no existe.
# Intentar ejecutar `building_heights["Landmark 81"]` detendría el programa lanzando un error del tipo `KeyError`.
# Por esa razón, la línea se mantiene comentada.

building_heights = {
    "Burj Khalifa": 828,
    "Shanghai Tower": 632,
    "Abraj Al Bait": 601,
    "Ping An": 599,
    "Lotte World Tower": 554.5,
    "One World Trade": 541.3
}

# print(building_heights["Landmark 81"])

# ==================================================
# 4. EXPLICACIÓN
# ==================================================
# Muestra cómo validar la existencia de una clave antes de acceder a ella para evitar errores.
# Mediante el operador `in` en una estructura condicional `if`, se verifica si `"Landmark 81"` está presente.
# Como no existe dentro del diccionario, la condición evalúa a `False` y no imprime nada.

building_heights = {
    "Burj Khalifa": 828,
    "Shanghai Tower": 632,
    "Abraj Al Bait": 601,
    "Ping An": 599,
    "Lotte World Tower": 554.5,
    "One World Trade": 541.3
}

key_to_check = "Landmark 81"

if key_to_check in building_heights:
    print(building_heights["Landmark 81"])

# ==================================================
# 5. EXPLICACIÓN
# ==================================================
# Se añade una nueva clave `"energy"` con el valor `"Not a Zodiac element"` asignándola mediante corchetes.
# A continuación, el bloque condicional comprueba si `"energy"` existe con el operador `in`
# y, al confirmar que sí está presente, procede a imprimir su valor.

zodiac_elements = {
    "water": ["Cancer", "Scorpio", "Pisces"],
    "fire": ["Aries", "Leo", "Sagittarius"],
    "earth": ["Taurus", "Virgo", "Capricorn"],
    "air": ["Gemini", "Libra", "Aquarius"]
}

zodiac_elements["energy"] = "Not a Zodiac element"

if "energy" in zodiac_elements:
    print(zodiac_elements["energy"])

# ==================================================
# 6. EXPLICACIÓN
# ==================================================
# Demuestra el uso del método `.get()` para buscar valores sin riesgo de detener el programa.
# Para una clave existente como `"Shanghai Tower"`, devuelve directamente su valor (`632`).
# Para una clave inexistente como `"My House"`, devuelve la palabra clave `None` en lugar de romper la ejecución.

building_heights = {
    "Burj Khalifa": 828,
    "Shanghai Tower": 632,
    "Abraj Al Bait": 601,
    "Ping An": 599,
    "Lotte World Tower": 554.5,
    "One World Trade": 541.3
}

print(building_heights.get("Shanghai Tower"))
print(building_heights.get("My House"))

# ==================================================
# 7. EXPLICACIÓN
# ==================================================
# Utiliza `.get()` para buscar el ID de un usuario en un diccionario.
# Mediante una estructura `if/else`, evalúa si el resultado devuelto es `None`.
# Como `"teraCoder"` sí existe, asigna su ID correspondiente a la variable `tc_id` y lo imprime en consola.

user_ids = {
    "teraCoder": 100019,
    "pythonGuy": 182921,
    "samTheJavaMaam": 123112,
    "lyleLoop": 102931,
    "keysmithKeith": 129384
}

print(user_ids.get("teraCoder"))

if user_ids.get("teraCoder") == None:
    tc_id = 1000
else:
    tc_id = user_ids.get("teraCoder")

print(tc_id)

# ==================================================
# 8. EXPLICACIÓN
# ==================================================
# Muestra el comportamiento de `.get()` cuando busca un usuario que no existe (`"superStackSmash"`).
# Al devolver `None`, la condición `if user_ids.get(...) == None` se cumple, ejecutando la asignación
# de un valor por defecto o predeterminado (`100000`) a la variable `stack_id`.

user_ids = {
    "teraCoder": 100019,
    "pythonGuy": 182921,
    "samTheJavaMaam": 123112,
    "lyleLoop": 102931,
    "keysmithKeith": 129384
}

if user_ids.get("superStackSmash") == None:
    stack_id = 100000

print(stack_id)

# ==================================================
# 9. EXPLICACIÓN
# ==================================================
# Muestra el funcionamiento del método `.pop()`, el cual elimina una clave y retorna su valor.
# Elimina la clave `320291` y muestra `"Gift Basket"`.
# Al incluir `"No Prize"` como segundo argumento, se define una respuesta por defecto por si la clave no existiera.
# Finalmente, imprime el diccionario modificado.

raffle = {
    223842: "Teddy Bear",
    872921: "Concert Tickets",
    320291: "Gift Basket",
    412123: "Necklace",
    298787: "Pasta Maker"
}

print(raffle.pop(320291, "No Prize"))
print(raffle)

# ==================================================
# 10. EXPLICACIÓN
# ==================================================
# Demuestra la seguridad de `.pop()` cuando se le pasa un valor por defecto (`"No Prize"`).
# Al intentar eliminar la clave `100000` (la cual no existe), el método devuelve el texto predeterminado
# en lugar de lanzar un error. El diccionario `raffle` permanece intacto.

raffle = {
    223842: "Teddy Bear",
    872921: "Concert Tickets",
    412123: "Necklace",
    298787: "Pasta Maker"
}

print(raffle.pop(100000, "No Prize"))
print(raffle)

# ==================================================
# 11. EXPLICACIÓN
# ==================================================
# Se vuelve a utilizar `.pop()` para extraer y eliminar otra clave específica (`872921`).
# Muestra por pantalla el valor eliminado (`"Concert Tickets"`) y finaliza imprimiendo
# el estado actual del diccionario tras las eliminaciones.

raffle = {
    223842: "Teddy Bear",
    872921: "Concert Tickets",
    412123: "Necklace",
    298787: "Pasta Maker"
}

print(raffle.pop(872921, "No Prize"))
print(raffle)

# ==================================================
# 12. EXPLICACIÓN
# ==================================================
# Simula un sistema de inventario de juego donde usar un ítem lo elimina del diccionario y aplica su efecto.
# Extrae y elimina `"stamina grains"` (+15) y `"power stew"` (+30), sumándolos a `health_points`.
# Para `"mystic bread"`, al no existir, `.pop()` devuelve el `0` predeterminado.
# Imprime el inventario restante y la vida total final.

available_items = {
    "health potion": 10,
    "cake of the cure": 5,
    "green elixir": 20,
    "strength sandwich": 25,
    "stamina grains": 15,
    "power stew": 30
}

health_points = 20

health_points += available_items.pop("stamina grains", 0)
health_points += available_items.pop("power stew", 0)
health_points += available_items.pop("mystic bread", 0)

print(available_items)
print(health_points)

# ==================================================
# 13. EXPLICACIÓN
# ==================================================
# Muestra cómo extraer de forma rápida el conjunto de claves de un diccionario.
# Al envolver el diccionario dentro de la función `list()`, Python extrae automáticamente
# únicamente las claves (los nombres de los estudiantes) y crea una lista convencional con ellas.

test_scores = {
    "Grace": [80, 72, 90],
    "Jeffrey": [88, 68, 81],
    "Sylvia": [80, 82, 84],
    "Pedro": [98, 96, 95],
    "Martin": [78, 80, 78],
    "Dina": [64, 60, 75]
}

print(list(test_scores))

# ==================================================
# 14. EXPLICACIÓN
# ==================================================
# Utiliza el método `.keys()` junto a un bucle `for` para iterar de manera explícita sobre las claves.
# En cada repetición del ciclo, la variable `student` toma el nombre de un estudiante
# e imprime dicho nombre en una línea individual.

test_scores = {
    "Grace": [80, 72, 90],
    "Jeffrey": [88, 68, 81],
    "Sylvia": [80, 82, 84],
    "Pedro": [98, 96, 95],
    "Martin": [78, 80, 78],
    "Dina": [64, 60, 75]
}

for student in test_scores.keys():
    print(student)

# ==================================================
# 15. EXPLICACIÓN
# ==================================================
# Muestra cómo usar `.keys()` para obtener una vista (dict_keys) de las claves presentes en distintas estructuras.
# Extrae las claves del diccionario `user_ids` y las guarda en `users`.
# Extrae las claves del diccionario `num_exercises` y las guarda en `lessons`, imprimiendo ambas secuencias.

user_ids = {
    "teraCoder": 100019,
    "pythonGuy": 182921,
    "samTheJavaMaam": 123112,
    "lyleLoop": 102931,
    "keysmithKeith": 129384
}

num_exercises = {
    "functions": 10,
    "syntax": 13,
    "control flow": 15,
    "loops": 22,
    "lists": 19,
    "classes": 18,
    "dictionaries": 18
}

users = user_ids.keys()
lessons = num_exercises.keys()

print(users)
print(lessons)

# ==================================================
# 16. EXPLICACIÓN
# ==================================================
# Utiliza el método `.values()` para acceder exclusivamente a los valores almacenados en el diccionario.
# A través de un bucle `for`, recorre cada elemento ignorando las claves (nombres) e imprimiendo únicamente
# las listas de calificaciones (`score_list`) de cada estudiante.

test_scores = {
    "Grace": [80, 72, 90],
    "Jeffrey": [88, 68, 81],
    "Sylvia": [80, 82, 84],
    "Pedro": [98, 96, 95],
    "Martin": [78, 80, 78],
    "Dina": [64, 60, 75]
}

for score_list in test_scores.values():
    print(score_list)

# ==================================================
# 17. EXPLICACIÓN
# ==================================================
# Utiliza un bucle `for` junto con el método `.values()` para acumular datos numéricos.
# Recorre la cantidad de ejercicios de cada lección y los va sumando progresivamente en la variable `total_exercises`.
# Imprime el resultado total al finalizar el recorrido.

num_exercises = {
    "functions": 10,
    "syntax": 13,
    "control flow": 15,
    "loops": 22,
    "lists": 19,
    "classes": 18,
    "dictionaries": 18
}

total_exercises = 0

for exercises in num_exercises.values():
    total_exercises += exercises

print(total_exercises)

# ==================================================
# 18. EXPLICACIÓN
# ==================================================
# Muestra el uso del método `.items()`, el cual devuelve pares tupla de (clave, valor) en cada iteración.
# Permite asignar simultáneamente la empresa a la variable `company` y su cifra a `value`.
# Imprime una cadena formateada concatenando ambos datos.

biggest_brands = {
    "Apple": 184,
    "Google": 141.7,
    "Microsoft": 80,
    "Coca-Cola": 69.7,
    "Amazon": 64.8
}

for company, value in biggest_brands.items():
    print(company + " has a value of " + str(value) + " billion dollars.")

# ==================================================
# 19. EXPLICACIÓN
# ==================================================
# Aplica `.items()` para desempaquetar simultáneamente la clave (`occupation`) y su valor (`percentage`).
# Dentro del bucle `for`, utiliza la conversión `str()` para transformar los números a texto
# y construir una oración descriptiva por cada profesión en la lista.

pct_women_in_occupation = {
    "CEO": 28,
    "Engineering Manager": 9,
    "Pharmacist": 58,
    "Physician": 40,
    "Lawyer": 37,
    "Aerospace Engineer": 9
}

for occupation, percentage in pct_women_in_occupation.items():
    print("Women make up " + str(percentage) + " percent of " + occupation + "s.")