# -*- coding: utf-8 -*-
"""Listas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l4RpE5X-lnCrffpio5Vw6MOY2-C5lxvl
"""

# ==================================================
# 1. CREAR UNA LISTA
# ==================================================
# Se define e inicializa la lista 'my_lista' con seis nombres de colores en formato de texto.
# Luego se imprime la lista completa y se utiliza la función `type()` para confirmar que la variable es de tipo lista (`list`).

my_lista = [
    'Rojo',
    'Azul',
    'Amarillo',
    'Naranja',
    'Violeta',
    'Verde'
]

print(my_lista)
print(type(my_lista))

# ==================================================
# 2. ACCEDER A UN ELEMENTO
# ==================================================
# Muestra cómo acceder a un elemento específico dentro de la lista utilizando su posición de índice entre corchetes.
# Dado que la indexación en Python inicia en 0, `my_lista[2]` accede e imprime el tercer elemento ('Amarillo').

my_lista = ['Rojo', 'Azul', 'Amarillo', 'Naranja', 'Violeta', 'Verde']

print(my_lista[2])

# ==================================================
# 3. SABER EL TAMAÑO DE LA LISTA
# ==================================================
# Utiliza la función integrada `len()` para calcular la cantidad total de elementos presentes en la lista.
# Muestra por pantalla el texto "my_lista size:" seguido del valor numérico devuelto por la función.

my_lista = ['Rojo', 'Azul', 'Amarillo', 'Naranja', 'Violeta', 'Verde']

print("my_lista size:", len(my_lista))

# ==================================================
# 4. OBTENER UNA PARTE DE LA LISTA
# ==================================================
# Muestra la técnica de rebanado (slicing) para extraer una sublista.
# `my_lista[0:2]` extrae desde el índice 0 hasta antes del índice 2.
# Omitir el índice inicial como en `my_lista[:2]` realiza exactamente la misma acción por defecto desde el inicio.

my_lista = ['Rojo', 'Azul', 'Amarillo', 'Naranja', 'Violeta', 'Verde']

print(my_lista[0:2])
print(my_lista[:2])

# ==================================================
# 5. append() → AGREGAR AL FINAL
# ==================================================
# Utiliza el método `.append()` para modificar la lista añadiendo un nuevo elemento ('Blanco') al final de la misma.
# Posteriormente imprime la lista actualizada para mostrar la inclusión.

my_lista = ['Rojo', 'Azul', 'Amarillo', 'Naranja', 'Violeta', 'Verde']

my_lista.append('Blanco')

print(my_lista)

# ==================================================
# 6. insert() → AGREGAR EN UNA POSICIÓN
# ==================================================
# Aplica el método `.insert(posición, elemento)` para colocar el valor 'Negro' en el índice 3.
# Esto desplaza los elementos posteriores hacia la derecha para hacer espacio en esa posición exacta.

my_lista = ['Rojo', 'Azul', 'Amarillo', 'Naranja', 'Violeta', 'Verde', 'Blanco']

my_lista.insert(3, 'Negro')

print(my_lista)

# ==================================================
# 7. extend() → AGREGAR VARIOS ELEMENTOS
# ==================================================
# Utiliza el método `.extend()` pasando una lista como parámetro para concatenar múltiples elementos ('Marron', 'Gris') al final de la lista original de una sola vez.

my_lista = ['Rojo', 'Azul', 'Amarillo', 'Negro', 'Naranja', 'Violeta', 'Verde', 'Blanco']

my_lista.extend([
    'Marron',
    'Gris'
])

print(my_lista)

# ==================================================
# 8. index() → BUSCAR LA POSICIÓN
# ==================================================
# Emplea el método `.index()` para realizar la búsqueda de un valor dentro de la lista.
# Devuelve e imprime el número entero correspondiente al índice numérico donde se localiza la cadena 'Azul'.

my_lista = ['Rojo', 'Azul', 'Amarillo', 'Negro', 'Naranja', 'Violeta', 'Verde', 'Blanco', 'Marron', 'Gris']

print(my_lista.index('Azul'))

# ==================================================
# 9. remove() → ELIMINAR POR VALOR
# ==================================================
# Muestra cómo eliminar un elemento buscando directamente su valor mediante `.remove('Marron')`.
# Se advierte en comentario que buscar un valor inexistente (como 'Magenta') lanzaría un error del tipo `ValueError`.

my_lista = ['Rojo', 'Azul', 'Amarillo', 'Negro', 'Naranja', 'Violeta', 'Verde', 'Blanco', 'Marron', 'Gris']

# my_lista.remove('Magenta')

my_lista.remove('Marron')

print(my_lista)

# ==================================================
# 10. insert() EN UNA POSICIÓN QUE NO EXISTE
# ==================================================
# Demuestra el comportamiento seguro de `.insert()` al intentar usar un índice fuera de rango (índice 8).
# Si la posición indicada supera el tamaño actual de la lista, Python ajusta el comportamiento y añade el elemento al final.

my_lista = ['Rojo', 'Azul', 'Amarillo', 'Negro', 'Naranja', 'Violeta', 'Verde', 'Blanco', 'Gris']

my_lista.insert(8, 'Marron')

print(my_lista)

# ==================================================
# 11. pop() → ELIMINAR Y DEVOLVER
# ==================================================
# Utiliza `.pop()` sin argumentos para extraer y remover el último elemento de la lista, imprimiendo el elemento retirado.
# Luego recalcula y muestra la nueva longitud de la lista con `len()`.

my_lista = ['Rojo', 'Azul', 'Amarillo', 'Negro', 'Naranja', 'Violeta', 'Verde', 'Blanco', 'Gris', 'Marron']

print(my_lista.pop())

size = len(my_lista)

print("size =", size)

# ==================================================
# 12. REPETIR UNA LISTA
# ==================================================
# Utiliza el operador de multiplicación `*` sobre la lista para duplicar o triplicar sus elementos en secuencia.
# El resultado se asigna a `my_lista_3` e imprime la nueva estructura duplicada tres veces.

my_lista = ['Rojo', 'Azul', 'Amarillo', 'Negro', 'Naranja', 'Violeta', 'Verde', 'Blanco', 'Gris']

my_lista_3 = my_lista * 3

print("my_lista_3:", my_lista_3)

# ==================================================
# 13. ORDENAR UNA LISTA
# ==================================================
# Explica el funcionamiento in-place del método `.sort()`.
# Ordena la lista original internamente pero devuelve `None`. Al asignar `my_lista.sort()` a una variable, esta almacena `None` en lugar de una nueva lista.

my_lista = ['Rojo', 'Azul', 'Amarillo', 'Negro', 'Naranja', 'Violeta', 'Verde', 'Blanco', 'Gris']

print("Sort:")
print()

my_listaSort = my_lista.sort()

print(my_listaSort)

# ==================================================
# 14. ORDENAR UNA LISTA NUMÉRICA
# ==================================================
# Muestra el método `.sort()` aplicado sobre una lista de números enteros desordenados.
# Reorganiza directamente los elementos del contenedor de menor a mayor (orden ascendente) y los imprime.

my_NumList = [
    10, 9, 8, 7, 6,
    5, 4, 3, 2, 1
]

print("Ordering my_NumList:")

my_NumList.sort()

print(my_NumList)

# ==================================================
# 15. ORDENAR DE MAYOR A MENOR
# ==================================================
# Utiliza el argumento opcional `reverse=True` dentro del método `.sort()`.
# Esto invierte el comportamiento estándar, ordenando los valores numéricos de la lista en orden descendente (de mayor a menor).

my_NumList = [
    1, 2, 3, 4, 5,
    6, 7, 8, 9, 10
]

my_NumList.sort(reverse=True)

print("De mayor a menor:", my_NumList)