# -*- coding: utf-8 -*-
"""Tuplas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1arkMiI4ktu1Qw7cMaGYUiIhLWen4ABDc
"""

# ==================================================
# 16. CONVERTIR UNA LISTA EN TUPLA
# ==================================================
# Utiliza la función `tuple()` para transformar la lista 'my_lista' en una estructura inmutable de tipo tupla.
# Imprime un par de saltos de línea y el contenido final almacenado en 'my_tupla'.

my_lista = ['Rojo', 'Azul', 'Amarillo', 'Naranja', 'Violeta', 'Verde']

my_tupla = tuple(my_lista)

print()
print()
print("my_tuple:", my_tupla)

# ==================================================
# 17. ACCEDER A ELEMENTOS DE UNA TUPLA
# ==================================================
# Muestra cómo acceder a los elementos individuales de una tupla mediante su índice numérico usando corchetes.
# Imprime el primer elemento en la posición 0 ('Rojo') y el tercero en la posición 2 ('Amarillo').

my_tupla = ('Rojo', 'Azul', 'Amarillo', 'Naranja', 'Violeta', 'Verde')

print(my_tupla[0])
print(my_tupla[2])

# ==================================================
# 18. COMPROBAR SI UN ELEMENTO EXISTE
# ==================================================
# Utiliza el operador `in` para verificar si un valor ('Rojo') se encuentra presente dentro de 'my_tupla'.
# Devuelve e imprime un valor booleano (`True` si existe o `False` si no se encuentra).

my_tupla = ('Rojo', 'Azul', 'Amarillo', 'Naranja', 'Violeta', 'Verde')

print('Rojo' in my_tupla)

# ==================================================
# 19. CONTAR ELEMENTOS
# ==================================================
# Emplea el método `.count()` para calcular la cantidad exacta de veces que un valor específico ('Rojo') aparece dentro de la tupla.

my_tupla = ('Rojo', 'Azul', 'Amarillo', 'Naranja', 'Violeta', 'Verde')

print(my_tupla.count('Rojo'))

# ==================================================
# 20. TUPLA DE UN SOLO ELEMENTO
# ==================================================
# Advierte que escribir un texto entre paréntesis `('Blanco')` no genera una tupla sino un simple `str`.
# Para que Python lo reconozca como tupla unitaria se debe incluir una coma final `('Blanco',)` o definir la variable.

my_tupla_unitaria = ('Blanco')

print(my_tupla_unitaria)

# ==================================================
# 21. EMPAQUETADO DE TUPLA
# ==================================================
# Muestra el concepto de empaquetado (packing) al definir una tupla separando valores por comas sin necesidad de usar paréntesis.
# Asigna múltiples tipos de datos a 'my_tupla' e imprime la tupla resultante.

my_tupla = 'Gaspar', 5, 8, 1999

print(my_tupla)

# ==================================================
# 22. DESEMPAQUETADO DE TUPLA
# ==================================================
# Demuestra el desempaquetado (unpacking) al asignar cada uno de los valores contenidos en la tupla a variables individuales (`nombre`, `dia`, `mes`, `año`).
# Imprime cada variable por separado y luego las combina en una sola salida de texto.

my_tupla = ('Gaspar', 5, 8, 1999)

nombre, dia, mes, año = my_tupla

print(nombre)
print(dia)
print(mes)
print(año)

print(
    "Nombre:", nombre,
    "- Dia:", dia,
    "- Mes:", mes,
    "- Año:", año
)

# ==================================================
# 23. CONVERTIR UNA TUPLA EN LISTA
# ==================================================
# Utiliza la función integrada `list()` para transformar la tupla 'my_tupla' nuevamente en una lista mutable.
# Guarda el resultado en 'my_lista2' y la muestra en pantalla.

my_tupla = ('Gaspar', 5, 8, 1999)

my_lista2 = list(my_tupla)

print(my_lista2)