# -*- coding: utf-8 -*-
"""Copia de Uudmy16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13PlU8gNW7ppaHboX0wcXMlP5aPTv3R36

Este bloque de código importa la librería `pandas` y carga un archivo Excel llamado 'Nba Teams.xlsx' en un DataFrame. Luego, elimina las filas que tienen todos sus valores nulos y muestra las primeras filas del DataFrame.
"""

import pandas as pd
#nba = pd.read_excel("Nba Teams.xlsx")
nba = pd.read_excel("/content/drive/MyDrive/udmy/dataAnalisys/Nba Teams.xlsx").dropna(how = "all")
nba

"""Este bloque de código monta Google Drive en el entorno de Colab, permitiendo el acceso a archivos almacenados en Drive."""

from google.colab import drive
drive.mount('/content/drive')

"""Este bloque de código muestra un resumen conciso del DataFrame, incluyendo el tipo de datos de cada columna y la cantidad de valores no nulos, lo cual es útil para entender la estructura de los datos y detectar valores faltantes."""

nba.info()

"""Este bloque de código reemplaza los valores nulos (NaN) en la columna 'Height' por la cadena 'Missing'. Esto es útil para manejar datos faltantes y evitar errores en operaciones futuras. Sin embargo, no se asigna el resultado de esta operación al DataFrame, por lo que la columna 'Height' no se modificará permanentemente."""

nba["Height"].fillna("Missing")