# -*- coding: utf-8 -*-
"""Copia de udmy7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PtRNBNa-KgyLt-0q8G6eq2JPAIPzhfSW

## Carga Inicial de Datos

En esta celda, se carga un archivo Excel llamado `Nba Teams.xlsx` en un DataFrame de pandas llamado `nba`. Luego, se muestran las primeras 5 filas del DataFrame para tener una vista previa de los datos.
"""

import pandas as pd
nba = pd.read_excel("Nba Teams.xlsx")
nba.head()

"""## Creación de Nuevas Columnas

Aquí se añaden dos nuevas columnas, `Teams` y `nba Teams`, al DataFrame `nba`. Ambas columnas se inicializan con cadenas de texto vacías. Finalmente, se muestran las primeras 5 filas del DataFrame para verificar los cambios.
"""

nba["Teams"] = " "
nba["nba Teams"] = " "
nba.head()

"""## Visualización de la Columna 'Teams'

Esta celda muestra el contenido de la columna `Teams` del DataFrame `nba`. Las líneas comentadas (`#nba.Name`, `#nba.nba Teams`, `#nba.Sports`) son ejemplos de cómo se podrían visualizar otras columnas, pero solo `nba.Teams` está activa.
"""

#nba.Name
#nba.nba Teams
nba.Teams
#nba.Sports

"""## Añadir y Mostrar la Columna 'Sports'

En esta celda, se crea una nueva columna llamada `Sports` y se le asigna el valor 'basket' a todas sus filas. Luego, se muestran las primeras 5 filas del DataFrame para ver la columna recién añadida y su contenido.
"""

nba["Sports"] = "basket"
nba.head()

"""## Eliminación de la Columna 'Teams'

Esta celda elimina la columna 'Teams' del DataFrame `nba` utilizando el método `drop()` con `axis=1` para indicar que se está eliminando una columna y `inplace=True` para aplicar el cambio directamente al DataFrame. Las líneas comentadas muestran intentos previos de inserción de columnas. Finalmente, se imprime el DataFrame completo para verificar que la columna 'Teams' ha sido eliminada.
"""

nba.drop("Teams", axis = 1, inplace = True)
#nba.insert(2, column = "Teams", value = "Colombians")
#nba.insert(2, column = "Sportss", value = "Turmequé")
nba

"""## Mostrar el DataFrame Actualizado

Esta celda simplemente imprime el DataFrame `nba` completo para mostrar su estado actual después de la operación anterior (eliminación de la columna 'Teams').
"""

nba

"""## Re-inserción de la Columna 'Teams'

Aquí se re-inserta una columna llamada `Teams` en la posición de índice 2 (después de la columna 'Team') y se le asigna el valor 'Colombians' a todas sus filas. Esto demuestra cómo se puede insertar una columna en una posición específica con un valor predeterminado.
"""

nba.insert(2, column = "Teams", value = "Colombians")

"""## Mostrar el DataFrame con la Columna 'Teams' Re-insertada

Esta celda imprime el DataFrame `nba` completo para confirmar que la columna 'Teams' ha sido re-insertada correctamente en la posición deseada con los valores especificados.
"""

nba

"""## Fin del Cuaderno

Esta es una celda vacía para marcar el final de las operaciones realizadas en este cuaderno.
"""

