# -*- coding: utf-8 -*-
"""Copia de udmy9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xf88JL-F5iWvnUnoRL3BDhjhe_RGPo2g

### Montar Google Drive

Este bloque de código monta tu Google Drive en el entorno de Colab, permitiendo acceder a los archivos almacenados allí.
"""

import pandas as pd
nba = pd.read_excel('/content/drive/MyDrive/udmy/dataAnalisys/Nba Teams.xlsx')
#nba.tail()
nba

"""### Obtener información del DataFrame

Este bloque de código utiliza el método `.info()` para mostrar un resumen conciso del DataFrame `nba`, incluyendo el tipo de dato de cada columna, el número de valores no nulos y el uso de memoria.
"""

from google.colab import drive
drive.mount('/content/drive')

"""### Cargar los datos del archivo Excel

Este bloque de código utiliza la biblioteca `pandas` para leer el archivo 'Nba Teams.xlsx' y cargarlo en un DataFrame llamado `nba`. Luego, muestra el DataFrame.
"""

nba.info()

"""### Verificar valores nulos

Este bloque de código utiliza el método `.isnull()` para crear un DataFrame booleano que indica la presencia de valores nulos (True) o no nulos (False) en cada celda del DataFrame `nba`.
"""

nba.isnull()

"""### Contar valores nulos por columna

Este bloque de código utiliza `.isnull().sum()` para contar el número total de valores nulos en cada columna del DataFrame `nba`, lo cual es útil para identificar columnas con datos faltantes.
"""

nba.isnull().sum()

"""### Celda vacía

Esta celda está vacía y puede usarse para futuros análisis o código.
"""

