# -*- coding: utf-8 -*-
"""Copia de udmy13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D_ToSV9mRYXW1j1G4SknJrdDX9jo97vX

### Montar Google Drive

Este bloque de código monta tu Google Drive en el entorno de Colab, lo que permite acceder a los archivos almacenados en él.
"""

import pandas as pd
nba = pd.read_excel('/content/drive/MyDrive/udmy/dataAnalisys/Nba Teams.xlsx')
nba.head()

"""### Contar Equipos

Este bloque de código cuenta la frecuencia de cada equipo en la columna 'Team' del DataFrame `nba` y muestra los resultados. Esto ayuda a ver cuántos jugadores hay por equipo.
"""

from google.colab import drive
drive.mount('/content/drive')

"""### Cargar Datos de la NBA

Este bloque de código utiliza la librería `pandas` para leer un archivo de Excel llamado 'Nba Teams.xlsx' desde tu Google Drive. Luego, muestra las primeras 5 filas del DataFrame resultante (`nba`) para una vista previa de los datos.
"""

nba["Team"].value_counts()

"""### Contar Divisiones

Este bloque de código cuenta la frecuencia de cada división en la columna 'Division' del DataFrame `nba` y muestra los resultados en orden ascendente. Esto ayuda a entender la distribución de jugadores por división.
"""

#nba["Division"].value_counts()
nba["Division"].value_counts(ascending = True)

"""### Celda Vacía

Esta celda está vacía y puede ser usada para futuros análisis o código.
"""

