# -*- coding: utf-8 -*-
"""Copia de udmy19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wb7NCSbq52_B-c1eapTpJVQmjYzZ1hRd

## Montar Google Drive

Este bloque de código monta tu Google Drive en el entorno de Colab, permitiendo que el notebook acceda a archivos almacenados en Drive.
"""

#Refine Dataframe using Multiple Conditions AND

import pandas as pd

#insta = pd.read_csv('/content/drive/MyDrive/udmy/dataAnalisys/Instagram.csv')
insta = pd.read_csv('/content/drive/MyDrive/udmy/dataAnalisys/Instagram.csv', parse_dates = ["reg date", "last login"])
insta["gender"] = insta["gender"].astype("category")
insta["Country"] = insta["Country"].astype("category")
insta["Influencer"] = insta["Influencer"].astype("bool")

insta.head()

"""## Filtrar DataFrame con Múltiples Condiciones

Este bloque de código filtra el DataFrame `insta` para seleccionar usuarios masculinos que se registraron después del 31 de diciembre de 2015 y son de 'United States'. Aplica todas las condiciones directamente en una sola máscara y muestra el resultado.
"""

from google.colab import drive
drive.mount('/content/drive')

"""## Cargar y Refinar el DataFrame

Este código carga un archivo CSV llamado 'Instagram.csv' en un DataFrame de pandas. También convierte las columnas 'reg date' y 'last login' a tipo datetime, y las columnas 'gender', 'Country' e 'Influencer' a tipos categóricos o booleanos para una gestión de datos más eficiente. Finalmente, muestra las primeras filas del DataFrame.
"""

#Print our Male instagram users that joined since 2016 and they are from USA

mask = (insta["gender"] == "Male") & (insta["reg date"] > "2015-12-31") & (insta["Country"] == "United States")
insta[mask]

"""## Filtrar DataFrame Usando Máscaras Separadas

Similar al bloque anterior, este código filtra el DataFrame `insta` para encontrar los mismos criterios: hombres registrados después de 2015 y de 'United States'. Sin embargo, en este caso, cada condición se define como una máscara separada (`mask1`, `mask2`, `mask3`) y luego se combinan para realizar el filtrado. El resultado debería ser idéntico al del bloque de código anterior, demostrando otra forma de aplicar múltiples condiciones.
"""

mask1 = insta["gender"] == "Male"
mask2 = insta["reg date"] > "2015-12-31"
mask3 = insta["Country"] == "United States"
insta[mask1 & mask2 & mask3]

"""## Demostración de Filtrado (Nota sobre Sensibilidad a Mayúsculas/Minúsculas)

Este código intenta filtrar usuarios masculinos registrados después del 31 de diciembre de 2015. Sin embargo, debido a que la condición para el género usa 'male' (minúsculas) en lugar de 'Male' (mayúsculas) como se encuentra en los datos, el filtro no encuentra ninguna coincidencia y devuelve un DataFrame vacío. Esto demuestra la importancia de la sensibilidad a mayúsculas y minúsculas en las cadenas de texto al filtrar datos.
"""

mask = (insta["gender"] == "male") & (insta["reg date"] > "2015-12-31")
insta[mask]