# -*- coding: utf-8 -*-
"""Copia de udmy17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ooFhw6f9Zg9BPSINsZ7tK1zFsHY-lBRj

## Carga y exploración inicial de datos

Este bloque de código carga el archivo CSV `fortune1000.csv` en un DataFrame de pandas. Primero, se carga sin un índice específico, y luego se recarga especificando la columna 'Rank' como índice. Finalmente, se muestra el DataFrame completo.
"""

import pandas as pd
fortune = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/fortune1000.csv")
fortune = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/fortune1000.csv", index_col = "Rank")
fortune

"""### Información del DataFrame

Esta celda muestra un resumen conciso del DataFrame `fortune`, incluyendo el tipo de dato de cada columna, el número de valores no nulos y el uso de memoria. Esto es útil para una primera inspección de los datos y para identificar columnas con valores faltantes.
"""

fortune.info()

"""### Visualización de las primeras filas

Aquí se muestran las primeras 3 filas del DataFrame `fortune`. Esto permite ver rápidamente la estructura de los datos y cómo se han cargado las columnas.
"""

fortune.head(3)

"""### Agrupación por 'Sector'

Este código realiza una operación de `groupby` en el DataFrame `fortune` utilizando la columna 'Sector'. Esto crea un objeto `DataFrameGroupBy` que permite realizar operaciones agregadas en cada grupo. Se muestra el tipo del objeto resultante.
"""

fortune.groupby('Sector')
x = fortune.groupby('Sector')
type(x)
x

"""### Recarga de datos y agrupación

En esta celda, se vuelve a cargar el archivo CSV en un nuevo DataFrame llamado `df` (sin establecer 'Rank' como índice inicialmente) y luego se agrupa por la columna 'Sector', asignando el resultado a la variable `sector`. Se muestran las primeras 5 filas del `df` para verificar la carga.
"""

import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/fortune1000.csv")
sector = df.groupby('Sector')
df.head(5)

"""### Objeto `DataFrameGroupBy`

Esta celda simplemente muestra la representación del objeto `sector` para confirmar que es un `DataFrameGroupBy`.
"""

sector

"""### Sectores únicos

Aquí se obtienen y muestran todos los valores únicos presentes en la columna 'Sector' del DataFrame `df`. Esto nos da una idea de la diversidad de sectores representados en los datos.
"""

df["Sector"].unique()

"""### Conteo de empresas por Sector

Esta celda calcula el número de empresas en cada sector utilizando el método `size()` en el objeto `groupby` `sector`. Esto nos indica cuántas entradas hay para cada sector.
"""

sector.size()

"""### Distribución de empresas por Sector

Similar a la celda anterior, `value_counts()` en la columna 'Sector' proporciona el número de ocurrencias para cada sector, lo que es útil para entender la distribución de empresas en los diferentes sectores.
"""

df["Sector"].value_counts()

"""### Primera empresa por Sector

El método `first()` aplicado al objeto `groupby` `sector` devuelve la primera fila (empresa) de cada grupo (sector). Esto puede ser útil para ver un representante de cada categoría según el orden original del DataFrame.
"""

sector.first()

"""### Última empresa por Sector

De manera similar a `first()`, `last()` devuelve la última fila (empresa) de cada grupo (sector). Esto muestra el último representante de cada categoría según el orden original del DataFrame.
"""

sector.last()

"""### Obtener un grupo específico

Estas líneas demuestran cómo seleccionar y visualizar todas las empresas que pertenecen a un sector específico utilizando el método `get_group()`.
"""

sector.get_group("Retailing")
sector.get_group("Health Care")
#sector.get_group("Energy")

"""### Filtrado por Sector

Aquí se crea una máscara booleana para seleccionar todas las filas donde la columna 'Sector' es 'Energy' y luego se aplica esta máscara al DataFrame `df` para mostrar solo esas empresas.
"""

df["Sector"] == "Energy"
mask = df["Sector"] == "Energy"
df[mask]

"""### Reasignación del DataFrame

En esta celda, el DataFrame `df` se asigna de nuevo a la variable `fortune`, posiblemente para asegurar que todas las operaciones posteriores se realicen en el mismo DataFrame. Luego se crea un nuevo objeto `groupby` llamado `sectors` basado en este `fortune` actualizado.
"""

#df.set_index("Rank", inplace = True)
df

"""### Estadísticas agregadas por Sector

Estas líneas calculan la suma de 'Employees' y la media de 'Employees' para cada sector. Muestra cómo realizar agregaciones básicas en grupos.
"""

sector.sum()
sector["Employees"].sum()
sector["Employees"].mean()

"""### Agregaciones múltiples por Sector

Esta celda demuestra el uso del método `agg()` para aplicar múltiples funciones de agregación a diferentes columnas de cada sector. Por ejemplo, calcula la media y el máximo de 'Revenues', el máximo y el mínimo de 'Profits', y la suma de 'Employees'.
"""

sector.agg({"Revenues" : "mean", "Profits" : "mean", "Employees" : "sum"})
sector.agg({"Revenues" : ["mean", "max"], "Profits" : "mean", "Employees" : "sum"})
sector.agg({"Revenues" : ["mean", "max"], "Profits" : ["max", "min"], "Employees" : "sum"})

"""### Preparación para la selección de las empresas con mayores ganancias

Aquí se asegura que `fortune` sea el DataFrame base y se vuelve a crear el objeto `sectors` para la agrupación. Esto es una preparación para la siguiente celda donde se intentará encontrar la empresa con mayores ganancias por sector.
"""

fortune = df
fortune
sectors = fortune.groupby('Sector')
fortune

"""### Conteo de elementos en los grupos de 'sectors'

Esta celda vuelve a calcular el tamaño de cada grupo (sector) en el DataFrame `fortune`.
"""

sector.size()

"""### Inicialización de un DataFrame vacío

Se crea un DataFrame `df` vacío con las mismas columnas que `fortune`. Este DataFrame se utilizará para almacenar los resultados de la siguiente operación.
"""

df = pd.DataFrame(columns = fortune.columns)
df

"""### Encontrar la empresa con mayores ganancias por sector (CORRECCIÓN)

Este bucle itera sobre cada sector y encuentra la empresa con las mayores ganancias (`Profits`) dentro de ese sector usando `nlargest(1, 'Profits')`. Se ha corregido el error `AttributeError: 'DataFrame' object has no attribute 'append'` usando `pd.concat` para añadir correctamente las empresas al DataFrame `df`.
"""

for sector, values in sectors:
  company_with_highest_profit = values.nlargest(1, "Profits")
  df = df.append(company_with_highest_profit)

