# -*- coding: utf-8 -*-
"""Copia de udmy16_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FiofVr1L26lj1iIj9dPUO4aj1y2uJv4w

## Cargar y mostrar los primeros datos

Este bloque de código carga un archivo CSV llamado `restaurant.csv` en un DataFrame de pandas y luego muestra las primeras filas del DataFrame para una vista previa rápida de los datos.
"""

import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/restaurant.csv")
df

"""## Información general del DataFrame

Esta celda utiliza el método `info()` para imprimir un resumen conciso del DataFrame, incluyendo el índice, el tipo de datos de cada columna, los valores no nulos y el uso de memoria.
"""

df.info()

"""## Valores únicos de la columna 'Gender'

Aquí se obtienen y muestran los valores únicos presentes en la columna 'Gender' para entender las categorías de género en el dataset.
"""

df["Gender"].unique()

"""## Suma y promedio del 'Amount' por 'Gender'

Este bloque de código utiliza `pivot_table` para calcular la suma total y el promedio del 'Amount' (cantidad) para cada categoría de 'Gender' (género).
"""

df.pivot_table(values = "Amount", index = "Gender", aggfunc="sum")
df.pivot_table(values = "Amount", index = "Gender", aggfunc="mean")

"""## Suma del 'Amount' por 'Menu'

Esta celda calcula la suma total del 'Amount' (cantidad) para cada tipo de 'Menu' utilizando una tabla pivote.
"""

df.pivot_table(values = "Amount", index = "Menu", aggfunc="sum")

"""## Suma del 'Amount' por 'Gender' y 'Menu'

Aquí se calcula la suma del 'Amount' agrupada por 'Gender' y luego por 'Menu', mostrando las cantidades totales para cada combinación.
"""

df.pivot_table(values = "Amount", index = ["Gender", "Menu"], aggfunc="sum")

"""## Suma del 'Amount' por 'Gender', 'Menu' y 'City'

Este bloque genera una tabla pivote que muestra la suma del 'Amount' para cada combinación de 'Gender' y 'Menu', desglosada por 'City' como columnas.
"""

df.pivot_table(values = "Amount", index = ["Gender", "Menu"], columns = "City", aggfunc="sum")

"""## Suma del 'Amount' por 'Gender', 'Menu', 'Frequency' y 'City'

Esta celda crea una tabla pivote compleja para analizar la suma del 'Amount' por 'Gender' y 'Menu', subdividida por 'Frequency' y 'City' en las columnas, lo que permite un análisis detallado.
"""

df.pivot_table(values = "Amount", index = ["Gender", "Menu"], columns = ["Frequency", "City"], aggfunc="sum")



