# -*- coding: utf-8 -*-
"""Copia de udmy16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kHNrnE8gp9k-Wv2ofO4i6H8fQopJfCRD

## Análisis de Datos de Empleados

A continuación, se realizará un análisis de datos de empleados, comenzando con la carga de los datos y una exploración inicial.
"""

import pandas as pd
emp = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Employee.csv")
emp.head()

"""Esta celda carga el archivo `Employee.csv` en un DataFrame de pandas llamado `emp` y muestra las primeras 5 filas para una vista previa de los datos."""

emp.info()

"""Aquí se utiliza el método `.info()` para obtener un resumen conciso del DataFrame, incluyendo el número de entradas no nulas y los tipos de datos de cada columna."""

emp.nunique()

"""Esta celda calcula el número de valores únicos para cada columna en el DataFrame `emp` usando el método `.nunique()`."""

emp[["department", "position"]] = emp[["department", "position"]].astype("category")

"""En esta celda, las columnas 'department' y 'position' se convierten al tipo de dato 'category' para optimizar la memoria y mejorar el rendimiento en operaciones con valores discretos."""

emp.info()

"""Se muestra nuevamente la información del DataFrame con `.info()` para confirmar que los tipos de datos de 'department' y 'position' han sido cambiados a 'category'."""

"happy".upper()
"PYTHON".lower()

"""Esta celda es una demostración sencilla de cómo usar los métodos de cadena `upper()` y `lower()` en Python para convertir texto a mayúsculas y minúsculas, respectivamente."""

emp["name"]
emp["name"].str.lower().str.title()

"""Aquí se aplica una serie de operaciones de cadena a la columna 'name'. Primero, se convierte todo a minúsculas (`.str.lower()`) y luego cada palabra se capitaliza (`.str.title()`) para un formato consistente.

Esta celda está vacía. Puede agregar aquí el siguiente paso en su análisis de datos o cualquier otro código relevante.
"""