# -*- coding: utf-8 -*-
"""Copia de udmy18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jZHm84kIBVjH5iiTyOtDViylPVO4Tjq-

### **Refinar el conjunto de datos por una condición**
"""

#Refine Dataset by a Condition

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

insta = pd.read_csv('/content/drive/MyDrive/udmy/dataAnalisys/Instagram.csv')
insta["reg date"] = pd.to_datetime(insta["reg date"])
insta["last login"] = pd.to_datetime(insta["last login"])
insta["gender"] = insta["gender"].astype("category")
insta["Country"] = insta["Country"].astype("category")
insta["Influencer"] = insta["Influencer"].astype("bool")
insta.info()

import pandas as pd

insta = pd.read_csv('/content/drive/MyDrive/udmy/dataAnalisys/Instagram.csv', parse_dates = ["reg date", "last login"])
insta["gender"] = insta["gender"].astype("category")
insta["Country"] = insta["Country"].astype("category")
insta["Influencer"] = insta["Influencer"].astype("bool")

insta.info()

insta.head(3)

insta[insta["gender"] == "Male"]
insta[insta["Country"] == "Australia"]

mask = insta["gender"] == "Female"
insta[mask]

insta[insta["Influencer"] == True]

mask1 = insta["Country"] != "United States"
insta[mask1]