# -*- coding: utf-8 -*-
"""Copia de udmy5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IF6vhlSOKiBau1AEHgG_t5WXFXWo8CfT

### Carga de datos y vista previa
Este bloque de código importa la librería `pandas`, lee el archivo "Nba Teams.xlsx" en un DataFrame llamado `nba` y muestra las primeras 5 filas para una vista previa de los datos.
"""

import pandas as pd
nba = pd.read_excel("Nba Teams.xlsx")
nba.head()

"""### Selección de la columna 'Name'
Este bloque de código selecciona y muestra la columna 'Name' del DataFrame `nba`.
"""

nba["Name"]

"""### Selección de la columna 'Salary'
Este bloque de código selecciona y muestra la columna 'Salary' del DataFrame `nba`.
"""

nba["Salary"]

"""### Otra forma de seleccionar la columna 'Name'
Este bloque de código también selecciona y muestra la columna 'Name' del DataFrame `nba`, utilizando la notación de punto.
"""

nba.Name

"""### Celda vacía
Esta celda de código está actualmente vacía. Puedes añadir código aquí para continuar con tu análisis.
"""

