# -*- coding: utf-8 -*-
"""Copia de udmy10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_97JcOF0W5O4K_MSERSuAk7sK__GeXbj

Este cuadro de código intenta cargar un archivo Excel llamado 'Nba Teams.xlsx' en un DataFrame de pandas y luego muestra las primeras filas. Sin embargo, en la primera ejecución, hubo un error porque Google Drive no estaba montado, lo que impedía el acceso al archivo.
"""

import pandas as pd
nba = pd.read_excel("/content/drive/MyDrive/udmy/AP005320241/Nba Teams.xlsx")
nba.head()

"""Este cuadro de código es esencial para permitir que Colab acceda a los archivos almacenados en tu Google Drive. Al ejecutarlo, se monta tu Drive en el entorno de Colab."""

from google.colab import drive
drive.mount('/content/drive')

"""En esta celda, se intenta montar Google Drive nuevamente (útil si la conexión se pierde o para forzar el remontaje) y, lo que es más importante, se muestran las primeras 10 filas del DataFrame 'nba'. Esto confirma que el archivo se ha cargado correctamente después de montar Drive."""

from google.colab import drive
drive.mount('/content/drive')
nba.head(10)

"""Este cuadro de código muestra las últimas 5 filas del DataFrame 'nba'. Es útil para tener una vista rápida de la cola de los datos y verificar su estructura general."""

nba.tail()

"""Aquí se crea un nuevo DataFrame llamado `nbaNoNull` eliminando todas las filas del DataFrame original `nba` que contienen al menos un valor nulo (`NaN`). Luego se muestra este nuevo DataFrame, que contendrá solo filas completas."""

nbaNoNull = nba.dropna()
nbaNoNull

"""Este cuadro de código vuelve a mostrar el DataFrame original `nba`. Esto es para demostrar que la operación `dropna()` en la celda anterior no modificó el DataFrame `nba` en su lugar, sino que devolvió una nueva copia."""

nba

"""Esta celda refuerza la demostración de que `nba.dropna()` sin el argumento `inplace=True` no altera el DataFrame original. Primero se llama a `dropna()` (que devuelve una copia modificada) y luego se imprime `nba`, mostrando que sigue siendo el DataFrame completo."""

#nba.dropna(inplace=True)
nba.dropna()
nba

"""Este cuadro de código utiliza `nba.info()` para proporcionar un resumen conciso del DataFrame. Incluye información sobre el número total de entradas, el recuento de valores no nulos por columna, los tipos de datos (Dtype) de cada columna y el uso de memoria."""

nba.info()

"""Este cuadro de código simplemente muestra el DataFrame `nba` completo, permitiéndonos ver su contenido después de las operaciones previas."""

nba

"""Aquí se utiliza `nba.dropna(how="all")`. Este comando elimina filas solo si *todas* las columnas de esa fila contienen valores nulos. Si una fila tiene al menos un valor no nulo, se mantiene. Luego se muestra el resultado."""

nba.dropna(how="all")

"""Este cuadro de código utiliza `nba.dropna(axis = 0)`, que es el comportamiento predeterminado de `dropna()`. Elimina cualquier fila que contenga *al menos un* valor nulo. Luego se muestra el DataFrame resultante."""

nba.dropna(axis = 0)

"""En este caso, se usa `nba.dropna(axis=1)`. Esto elimina cualquier columna que contenga *al menos un* valor nulo. El resultado es un DataFrame vacío porque, según la información anterior, todas las columnas tenían al menos un valor nulo."""

nba.dropna(axis=1)

"""Este cuadro de código elimina filas del DataFrame `nba` solo si tienen valores nulos (`NaN`) en las columnas específicas "Name", "Salary" o "College". Las filas que tienen valores nulos en otras columnas pero no en estas tres se mantienen. Luego se muestra el DataFrame resultante."""

nba.dropna(subset = ["Name", "Salary", "College"])

"""Hemos explorado diferentes formas de manejar valores nulos (`NaN`) utilizando el método `dropna()` de pandas. Esto incluye eliminar filas basadas en cualquier valor nulo, solo si todas las columnas son nulas, eliminar columnas con valores nulos, y eliminar filas basándose en valores nulos en un subconjunto específico de columnas."""

