# -*- coding: utf-8 -*-
"""Copia de udmy15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dmK3JFn-AbFQ2pc3tG7nhC-d4CQTfYRD

Este bloque de código carga un archivo Excel llamado 'Nba Teams.xlsx' en un DataFrame de pandas y luego lo ordena por las columnas 'Team' y 'Name'. La opción `na_position='first'` asegura que los valores nulos aparezcan al principio y `inplace=True` aplica los cambios directamente al DataFrame.
"""

import pandas as pd
nba = pd.read_excel('/content/drive/MyDrive/udmy/dataAnalisys/Nba Teams.xlsx')
nba.sort_values(["Team", "Name"], na_position = "first", inplace = True)
nba

"""Este bloque de código monta Google Drive en el entorno de Colab, lo que permite acceder a archivos almacenados en Drive, como el archivo 'Nba Teams.xlsx' utilizado anteriormente."""

from google.colab import drive
drive.mount('/content/drive')

"""Este bloque de código ordena el DataFrame `nba` por su índice. Esto revierte cualquier ordenamiento anterior y restaura el orden original de las filas según su índice numérico."""

nba.sort_index()

