# -*- coding: utf-8 -*-
"""Copia de udmy4_DataFrameFromFile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiG_VHiwbEJhxDNPGzr9H2elisxNIMaL

Cargando el archivo Excel 'Nba Teams.xlsx' en un DataFrame de pandas llamado `nba` y mostrando su contenido.
"""

import pandas as pd
nba = pd.read_excel('Nba Teams.xlsx')
nba

"""Mostrando información concisa sobre el DataFrame `nba`, incluyendo el tipo de datos de cada columna y el número de valores no nulos."""

nba.info()

"""Mostrando las primeras 5 filas del DataFrame `nba` para tener una vista previa de los datos."""

nba.head()

"""Mostrando información detallada (tipo de datos y valores no nulos) específicamente para las primeras 5 filas del DataFrame `nba`."""

nba.head(5).info()

