# -*- coding: utf-8 -*-
"""Copia de udmy3_Dataframe_from_Dictionary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lqr3CwyXptYfPdF4cJ4Yy9I9NBB3HATv

Esta celda importa la librería `pandas`, que es una herramienta fundamental para el análisis y manipulación de datos en Python. Se le asigna el alias `pd` para facilitar su uso.
"""

import pandas as pd

"""Aquí se define un diccionario llamado `data`. Este diccionario contiene tres listas, cada una representando una columna: 'name' (nombre), 'age' (edad) y 'gender' (género). Estos datos se utilizarán para crear un DataFrame."""

data = {"name": ["Sally", "Jhon", "Kim"], "age": [4, 6 ,7], "gender": ["female", "male", "male"]}

"""En esta celda, se crea un DataFrame de pandas a partir del diccionario `data` definido anteriormente. `pd.DataFrame(data)` convierte el diccionario en una estructura de tabla, donde las claves del diccionario se convierten en los nombres de las columnas y los valores en las filas correspondientes."""

pd.DataFrame(data)

"""Esta celda también crea un DataFrame a partir del diccionario `data`, pero con una adición importante: se especifican los índices de las filas de forma manual. En lugar de usar los índices numéricos predeterminados (0, 1, 2), se asignan etiquetas personalizadas como 'Kid1', 'Kid2' y 'Kid3'."""

pd.DataFrame(data, index = ["Kid1", "Kid2", "Kid3"])

