# -*- coding: utf-8 -*-
"""Copia de udmy11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZxGDHbIiscgQtnoKK5Pyckxh3uubc6xg

### Cargar los datos

Primero, importamos la librería `pandas` y cargamos el archivo 'Nba Teams.xlsx' en un DataFrame llamado `nba`.
"""

import pandas as pd
nba = pd.read_excel('/content/drive/MyDrive/udmy/dataAnalisys/Nba Teams.xlsx')

"""### Montar Google Drive

Esta celda monta Google Drive, lo cual permite acceder a los archivos almacenados en él, como el archivo 'Nba Teams.xlsx'.
"""

from google.colab import drive
drive.mount('/content/drive')

"""### Mostrar las primeras filas del DataFrame

Utilizamos `nba.head(10)` para mostrar las primeras 10 filas del DataFrame, lo que nos permite ver un vistazo rápido de los datos y sus columnas.
"""

nba.head(10)

"""### Rellenar todos los valores nulos

Aquí utilizamos `nba.fillna(0)` para reemplazar todos los valores nulos (NaN) en todo el DataFrame con el número 0. Esto es útil para limpiar los datos antes de realizar análisis.
"""

nba.fillna(0)

"""### Rellenar valores nulos en la columna 'College'

En esta celda, estamos específicamente rellenando los valores nulos solo en la columna 'College' con 0. El parámetro `inplace=True` asegura que los cambios se apliquen directamente al DataFrame `nba`.
"""

nba[["College"]].fillna(0, inplace = True)
nba

"""### Rellenar valores nulos en la columna 'Name'

Finalmente, rellenamos los valores nulos en la columna 'Name' con la cadena de texto 'Missing name'. Esto es útil para identificar fácilmente los nombres que faltan en el conjunto de datos.
"""

nba["Name"].fillna("Missing name", inplace = True)
nba