# -*- coding: utf-8 -*-
"""Copia de udmy18_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11kCo0eiVAnF0ThyUqe7Y7ktleNDRDaIL

### Carga de Datos

Este bloque de código importa la librería `pandas` y carga tres archivos CSV (cursos, notas y estudiantes) en DataFrames separados. Los archivos se leen desde la ruta especificada en Google Drive.
"""

import pandas as pd
courses = pd.read_csv('/content/drive/MyDrive/udmy/dataAnalisys/COLLEGE - Courses.csv')
grades = pd.read_csv('/content/drive/MyDrive/udmy/dataAnalisys/COLLEGE - Grades.csv')
students = pd.read_csv('/content/drive/MyDrive/udmy/dataAnalisys/COLLEGE - Students.csv')

"""### Visualización del DataFrame `courses`

Esta celda muestra el contenido completo del DataFrame `courses`, que contiene información sobre los cursos disponibles, sus nombres y el semestre en que se imparten.
"""

courses

"""### Primeras Filas del DataFrame `grades`

Aquí se muestran las primeras 5 filas del DataFrame `grades` para tener una vista previa de su estructura y contenido, que incluye las notas de los estudiantes y los IDs de los cursos.
"""

grades.head()

"""### Primeras Filas del DataFrame `students`

Esta celda muestra las primeras 5 filas del DataFrame `students`, que contiene información sobre los estudiantes como su ID, nombre, apellido y género.
"""

students.head()

"""### Combinación de DataFrames `students` y `grades`

En este bloque, se combinan los DataFrames `students` y `grades` utilizando la columna `student_id` como clave común. El resultado muestra las primeras 5 filas de este nuevo DataFrame combinado, que ahora incluye tanto la información del estudiante como sus notas y los IDs de los cursos en los que obtuvo esas notas.
"""

pd.merge(students, grades, on = 'student_id').head()

"""### Estudiantes con las Notas Más Altas

Esta celda combina los DataFrames `students` y `grades`, ordena los resultados por la columna `grade` en orden descendente y luego muestra las primeras 10 filas. Esto permite identificar a los estudiantes con las notas más altas.
"""

df = pd.merge(students, grades, on = 'student_id').sort_values('grade', ascending = False).head(10)
df.head()

"""### Filtrado por `student_id` (2332)

Aquí se filtra el DataFrame `df` (que contiene los 10 estudiantes con mejores notas) para mostrar solo las entradas correspondientes al `student_id` 2332. Esto permite ver las notas y cursos específicos de ese estudiante dentro del top 10.
"""

df['student_id'] == 2332
df[df['student_id'] == 2332]

"""### Filtrado por `student_id` (2368)

Similar a la celda anterior, este código filtra el DataFrame `df` para mostrar las entradas del `student_id` 2368, revelando sus notas y los cursos asociados dentro de los estudiantes con mejores calificaciones.
"""

df[df['student_id'] == 2368]

"""### Combinación Inicial de Estudiantes y Notas

Este bloque combina los DataFrames `students` y `grades` usando `student_id` como clave. El resultado, almacenado en `students_rec`, contiene la información de cada estudiante junto con todas sus notas y los IDs de los cursos. Luego se muestran las primeras filas.
"""

students_rec = students.merge(grades, on = 'student_id')
students_rec.head()

"""### Combinación con Información de Cursos

Aquí se combina el DataFrame `students_rec` (que ya tiene información de estudiantes y notas) con el DataFrame `courses` utilizando `course_id` como clave. El nuevo DataFrame `students_rec1` ahora incluye detalles completos de estudiantes, notas y los nombres de los cursos. Se muestran las primeras filas para verificar la fusión.
"""

students_rec1 = students_rec.merge(courses, on = 'course_id')
students_rec1.head()

"""### Conteo de Registros por Nombre de Curso

Este código agrupa el DataFrame `students_rec1` por `course_name` y cuenta el número de registros (estudiantes inscritos o notas registradas) para cada curso. Luego, ordena los resultados de menor a mayor para ver qué cursos tienen más o menos actividad.
"""

reg_course = students_rec1.groupby('course_name')
reg_course.size().sort_values()

"""### Agrupación por Múltiples Columnas

En esta celda, se crea una nueva agrupación del DataFrame `students_rec1` utilizando cuatro columnas: `course_name`, `last_name`, `first_name` y `grade`. Esto prepara los datos para un análisis más detallado a nivel de estudiante y curso.
"""

students_records = students_rec1.groupby(['course_name', 'last_name', 'first_name', 'grade'])

"""### Conteo de Registros en Agrupación Detallada

Esta celda calcula el tamaño (número de ocurrencias) de cada combinación única de `course_name`, `last_name`, `first_name` y `grade` de la agrupación `students_records`. Esto puede ayudar a identificar si hay duplicados o a entender la distribución de notas para cada estudiante en cada curso.
"""

students_records.size()

"""### Verificación del DataFrame `students_rec1`

Esta celda simplemente muestra las primeras filas del DataFrame `students_rec1` nuevamente para recordar su estructura y contenido después de las operaciones de combinación y agrupación anteriores.
"""

students_rec1.head()

"""### Vista Previa del DataFrame `grades`

Aquí se muestra las primeras filas del DataFrame `grades` para una referencia rápida. La línea comentada era un intento previo de fusión que fue descartado.
"""

grades.head()
#pd.merge(students_rec1, grades, left = 'id', right_on = 'student_id')

"""### Celda Vacía para Futuro Código

Esta celda está vacía y se puede usar para añadir código nuevo en el futuro, como un análisis adicional, una visualización o una limpieza de datos.
"""

