# -*- coding: utf-8 -*-
"""Copia de udmy2_Dataframes_from_List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/109cicnLdgATCxqUhjLwSfBYs8YLaQShT

Este bloque de código importa la librería `pandas`, que es fundamental para trabajar con DataFrames en Python.
"""

# Create dataframe from a list

import pandas as pd

"""Aquí se define una lista simple de números."""

numbers = [1, 2, 3, 4, 5, 6]

"""Este código crea un DataFrame de pandas a partir de la lista de números definida anteriormente. Los números se convierten en una sola columna."""

pd.DataFrame(numbers)

"""Este bloque de código define una lista de listas, donde cada sublista representa una fila de datos con un nombre y una edad."""

data = [["Jhon",  23], ["Mary", 18], ["Jhon", 31]]

"""Aquí se crea un DataFrame de pandas a partir de la lista de listas `data`. Por defecto, pandas asigna nombres de columna numéricos (0 y 1)."""

pd.DataFrame(data)

"""Este código crea un DataFrame a partir de `data`, pero esta vez se especifican los nombres de las columnas como 'name' y 'age', lo que mejora la legibilidad."""

pd.DataFrame(data, columns = ["name", "age"])

"""Finalmente, este bloque de código crea un DataFrame de la misma manera que el anterior, pero además, asigna índices personalizados ('id1', 'id2', 'id3') a cada fila en lugar de los índices numéricos predeterminados."""

pd.DataFrame(data, columns = ["name", "age"], index = ["id1", "id2", "id3"])