# -*- coding: utf-8 -*-
"""Copia de udmy8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v1svByke40HpEtXWl6WGtSteiJ9ti8--

Cargando el archivo 'Nba Teams.xlsx' en un DataFrame de pandas y mostrando las primeras 5 filas para una vista previa.
"""

import pandas as pd
nba = pd.read_excel("Nba Teams.xlsx")
nba.head()

"""Eliminando la columna 'Salary' del DataFrame. Ten en cuenta que esta operación no modifica el DataFrame original a menos que se use `inplace=True`."""

nba.drop("Salary", axis = 1)

"""Mostrando el DataFrame completo después de la operación anterior para verificar su estado actual."""

nba

"""Eliminando la columna 'Salary' del DataFrame de forma permanente, utilizando `inplace=True`."""

nba.drop("Salary", axis = 1, inplace = True)

"""Mostrando el DataFrame para confirmar que la columna 'Salary' ha sido eliminada permanentemente."""

nba

"""Eliminando las columnas 'Team' y 'Division' del DataFrame de forma permanente, utilizando `inplace=True`."""

nba.drop(["Team", "Division"], axis = 1, inplace = True)

"""Mostrando el DataFrame final para verificar que las columnas 'Team' y 'Division' han sido eliminadas."""

nba