# -*- coding: utf-8 -*-
"""Copia de udmy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EsXSm03etug_Yy_Y3f8Tw-UR00LOUtdN

### Carga de Datos

Esta celda carga los datos de COVID de Nueva York desde una URL pública en un DataFrame de pandas y muestra las primeras 5 filas para una vista previa rápida.
"""

import pandas as pd
url = "https://data.cityofnewyork.us/resource/rc75-m7u3.csv"
#covid = pd.read_csv(url)
covid = pd.read_csv(url)
covid.head()

"""### Información del DataFrame

Esta celda imprime un resumen conciso del DataFrame, incluyendo el número de entradas, el número de columnas, los tipos de datos de cada columna y la cantidad de valores no nulos.
"""

covid.info()

"""### Guardar DataFrame Completo en CSV

Esta celda guarda el DataFrame completo `covid` en un archivo CSV llamado 'NYC_covid_cases.csv' en el directorio actual.
"""

covid.to_csv('NYC_covid_cases.csv')

"""### Guardar Columnas Seleccionadas en CSV

Esta celda guarda solo las columnas 'case_count', 'hospitalized_count' y 'death_count' del DataFrame `covid` en un nuevo archivo CSV llamado 'NYC1_covid_cases.csv'.
"""

covid.to_csv('NYC1_covid_cases.csv', columns = ['case_count', 'hospitalized_count', 'death_count'])

"""### Próximo Paso

La celda siguiente está vacía. ¿Hay algo más que te gustaría hacer con estos datos o qué tarea te gustaría que realizara a continuación?
"""

