# -*- coding: utf-8 -*-
"""Copia de Uudmy17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJkCTXbV3EMP3MtW2df1DEpaAPPIAbmw

## Optimización del conjunto de datos

Este código se refiere a la optimización del conjunto de datos, probablemente como un título o un comentario general sobre la sección.
"""

#Optimizing dataset

"""### Montando Google Drive

Este código monta tu Google Drive en el entorno de Colab, permitiendo que el notebook acceda a los archivos almacenados en tu Drive.
"""

from google.colab import drive
drive.mount('/content/drive')

"""### Cargando el archivo CSV y mostrando las primeras filas

Aquí importamos la librería `pandas` para trabajar con DataFrames. Luego, leemos el archivo `Instagram.csv` desde Google Drive y mostramos las primeras 5 filas para una vista previa de los datos.
"""

import pandas as pd
insta = pd.read_csv('/content/drive/MyDrive/udmy/dataAnalisys/Instagram.csv')
insta.head()

"""### Obteniendo información del DataFrame

Este comando muestra un resumen conciso del DataFrame, incluyendo el número de entradas, el número de columnas, los tipos de datos de cada columna y el conteo de valores no nulos. Es útil para identificar valores faltantes y tipos de datos.
"""

insta.info()

"""### Volviendo a cargar el archivo CSV y mostrando el DataFrame completo

Este paso vuelve a cargar el archivo CSV y luego muestra todo el DataFrame. Aunque la carga inicial ya se hizo, esto asegura que estamos trabajando con el DataFrame completo y visualizando todos sus registros.
"""

insta = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Instagram.csv")
insta

"""### Convirtiendo la columna 'reg date' a formato de fecha

Aquí convertimos la columna 'reg date' al tipo de dato `datetime` usando `pd.to_datetime()`. Esto es crucial para realizar operaciones basadas en tiempo. Después de la conversión, se muestra el DataFrame actualizado.
"""

insta["reg date"] = pd.to_datetime(insta["reg date"])
insta

"""### Verificando la información del DataFrame después de la conversión de 'reg date'

Se utiliza `insta.info()` nuevamente para confirmar que la columna 'reg date' ha sido correctamente convertida a un tipo de dato `datetime`.
"""

insta.info()

"""### Convirtiendo la columna 'last login' a formato de fecha

De manera similar a la columna 'reg date', esta línea convierte la columna 'last login' a un tipo de dato `datetime`. Luego, `insta.info()` se usa para mostrar los tipos de datos actualizados de todas las columnas.
"""

insta["last login"] = pd.to_datetime(insta["last login"])
#insta.drop("last login", axis = 1, inplace = True)
insta.info()

"""### Contando valores únicos en la columna 'gender'

Este comando calcula y muestra el número de valores únicos presentes en la columna 'gender', lo cual es útil para entender la diversidad de categorías en esta variable.
"""

insta["gender"].nunique()

"""### Verificando la información del DataFrame

Se llama a `insta.info()` para obtener un resumen actualizado del DataFrame, incluyendo el tipo de datos de cada columna y la cantidad de valores no nulos.
"""

insta.info()

"""### Previsualizando la conversión de la columna 'gender' a tipo categórico

Este código muestra cómo se vería la columna 'gender' si se convierte a un tipo de dato categórico, pero no aplica el cambio de forma permanente todavía. Muestra las categorías detectadas.
"""

insta["gender"].astype("category")

"""### Convirtiendo la columna 'gender' a tipo categórico y verificando el DataFrame

Aquí aplicamos la conversión de la columna 'gender' a un tipo de dato categórico (`'category'`). Esto es eficiente para columnas con un número limitado de valores únicos. Luego, `insta.info()` confirma el cambio en el tipo de dato.
"""

insta["gender"] = insta["gender"].astype("category")
insta.info()

"""### Mostrando la columna 'Country'

Este comando simplemente muestra el contenido de la columna 'Country' del DataFrame, permitiendo inspeccionar los valores de los países.
"""

insta["Country"]



