# -*- coding: utf-8 -*-
"""Copia de udmy6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-X79ii_dTrNPK2-OCXtQjcltnhBCMa-E

### Carga de Datos

Este bloque de código importa la librería `pandas`, lee un archivo Excel llamado "Nba Teams.xlsx" en un DataFrame y luego muestra las primeras 5 filas del DataFrame para una vista previa de los datos.
"""

import pandas as pd
nba = pd.read_excel("Nba Teams.xlsx")
nba.head()

"""### Selección de Columnas (Nombre y Equipo)

Este bloque de código selecciona y muestra solo las columnas 'Name' y 'Team' del DataFrame `nba`.
"""

nba[["Name", "Team"]]

"""### Selección de Columnas (Nombre, Equipo y Salario)

Este bloque de código selecciona y muestra las columnas 'Name', 'Team' y 'Salary' del DataFrame `nba`.
"""

nba[["Name", "Team", "Salary"]]

