# -*- coding: utf-8 -*-
"""Copia de udmy12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qXJ75ZVPjX7f9BoysnSw_j-yeHK4aUFB

Este bloque de código importa la biblioteca pandas, que es esencial para la manipulación de datos en Python. Luego, carga los datos de un archivo Excel llamado 'Nba Teams.xlsx' en un DataFrame de pandas llamado 'nba'.
"""

import pandas as pd
nba = pd.read_excel('/content/drive/MyDrive/udmy/dataAnalisys/Nba Teams.xlsx')

"""Este código monta Google Drive en el entorno de Colab. Esto permite que el notebook acceda a archivos almacenados en tu Drive, como el archivo 'Nba Teams.xlsx'."""

from google.colab import drive
drive.mount('/content/drive')

"""Aquí, se accede y se muestra la columna 'Salary' (Salario) del DataFrame 'nba'. Esto permite ver los valores de salario para cada jugador."""

nba["Salary"]

"""En este paso, se suman 50.000 a cada valor de la columna 'Salary' utilizando el método `.add()`. Este es un ejemplo de cómo realizar operaciones aritméticas en una Serie de pandas."""

nba["Salary"].add(50000)

"""Este código realiza la misma operación de suma que el anterior, pero utilizando el operador aritmético `+` directamente. Se suman 2.000.000 a cada valor de la columna 'Salary'."""

nba["Salary"] + 2000000

"""Aquí se crea una nueva columna llamada 'bonus_salary' en el DataFrame 'nba'. Esta nueva columna se calcula sumando 30.000 a los valores de la columna 'Salary' existente y luego se muestra el DataFrame completo para ver la nueva columna."""

nba["bonus_salary"] = nba["Salary"] + 30000
nba

"""Este paso demuestra cómo restar un valor de una columna utilizando el método `.sub()`. Se restan 55.000 a cada salario de la columna 'Salary'."""

nba["Salary"].sub(55000)
#nba["Salary"] - sub(55000)

"""En este bloque, se divide cada salario de la columna 'Salary' por 1.000.000 utilizando el método `.div()`. Esto podría usarse, por ejemplo, para convertir salarios a millones."""

nba["Salary"].div(1000000)
#nba["Salary"]/1000000

"""Finalmente, este código multiplica cada valor de la columna 'Weight' (Peso) por 0.453592 utilizando el método `.mul()`. Esto probablemente se hace para convertir el peso de libras a kilogramos."""

nba["Weight"].mul(0.453592)
#nba["Weight"]*0.453592

