# -*- coding: utf-8 -*-
"""Copia de udmy14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h9oNT0g151BqpLagnuMYSoh3ErZ9u44I

### Montar Google Drive
Esta celda monta Google Drive en el entorno de Colab, lo que permite acceder a archivos almacenados en Drive.
"""

import pandas as pd
nba = pd.read_excel("/content/drive/MyDrive/udmy/dataAnalisys/Nba Teams.xlsx")
nba.head()

"""### Ordenar Datos por Nombre
Esta celda ordena el DataFrame `nba` alfabéticamente por la columna 'Name' y muestra las primeras 20 filas del resultado.
"""

from google.colab import drive
drive.mount('/content/drive')

"""### Cargar Datos y Mostrar las Primeras Filas
Esta celda utiliza la librería `pandas` para leer un archivo de Excel llamado `Nba Teams.xlsx` desde Google Drive. Luego, muestra las primeras 5 filas del DataFrame resultante (`nba`) para previsualizar los datos.
"""

nba.sort_values("Name").head(20)

"""### Ordenar Datos por Salario
Esta celda ordena el DataFrame `nba` por la columna 'Salary' en orden ascendente (por defecto). El código comentado (`#nba.sort_values("Salary", ascending = False, inplace = True)`) mostraría cómo ordenar en orden descendente y aplicar los cambios directamente al DataFrame.
"""

nba.sort_values("Salary")
#nba.sort_values("Salary", ascending = False, inplace = True)

"""### Ordenar Datos por Equipo y Nombre
Esta celda ordena el DataFrame `nba` primero por la columna 'Team' y luego por la columna 'Name' dentro de cada equipo. El código comentado (`#nba.sort_values(["Team", "Name"], na_position = 'first')`) mostraría cómo colocar los valores nulos al principio al ordenar.
"""

nba.sort_values(["Team", "Name"])
#nba.sort_values(["Team", "Name"], na_position = 'first')

